title: Dr. Brian Rivera
email: rivera21@stolaf.edu
description: >-
  Professor & Researcher 
baseurl: ""
url: "https://brivera21.github.io"
bluesky_username: "@brianrivera.bsky.social"
github_username: https://github.com/brivera21

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Navigation - this is the key part
header_pages:
  - about.md
  - research-lab.md
  - publications.md
  - cv.md
  - contact.md

# Make sure minima shows navigation
show_excerpts: true
