title: Dr. Brian Rivera
email: rivera21@stolaf.edu
description: Professor & Researcher
baseurl: ""
url: "https://brivera21.github.io"

# Navigation
header_pages:
  - about.md
  - research-lab.md
  - publications.md
  - cv.md
  - contact.md

markdown: kramdown
theme: minima
show_excerpts: false
