title: Dr. Brian Rivera
email: rivera21@stolaf.edu
description: Professor & Researcher
baseurl: ""
url: "https://brivera21.github.io"

markdown: kramdown
theme: minima

# Disable blog features
show_excerpts: false
